[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "FRONTEND_DOMAIN,FORMSPREE_ENDPOINT,RUPANTOR_API_KEY"

[dev]
  command = "npm run dev"
  targetPort = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
